version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-app}
      - POSTGRES_USER=${DB_USER:-app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-app}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend1:
    build: .
    container_name: backend1
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
      - DB_NAME=${DB_NAME:-app}
      - DB_USER=${DB_USER:-app}
      - DB_PASSWORD=${DB_PASSWORD:-app}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
    depends_on:
      - db

  backend2:
    build: .
    container_name: backend2
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
      - DB_NAME=${DB_NAME:-app}
      - DB_USER=${DB_USER:-app}
      - DB_PASSWORD=${DB_PASSWORD:-app}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
    depends_on:
      - db

  backend3:
    build: .
    container_name: backend3
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-1}
      - DB_NAME=${DB_NAME:-app}
      - DB_USER=${DB_USER:-app}
      - DB_PASSWORD=${DB_PASSWORD:-app}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3

volumes:
  pgdata:
